#### You have magically got your hands on some data.It happens to be jumbled up text regarding the one hundred most expensive schools in terms of tuition in the United States.

Upon close inspection, you realize that the file has values corresponding to the following. And the data in its raw form is as posted below


1. **Institution** -- the name of the school
2. **City** -- location of school, by city
3. **State** -- location of school, by state
4. **UnID** -- unique ID of the school
5. **Zip** --  location of the school, by zip
6. **Branches** -- number of campuses
7. **Region** --  location of school, by region
8. **HBCU** -- 1 if historically black, 0 otherwise
9. **MenOnly** -- 1 if men only, 0 otherwise
10. **WomenOnly** -- 1 if women only, 0 otherwise
11. **AdmissionRate** -- school's admission rate
12. **SATAvg** -- average SAT (if available). None if now
13. **TuitionFTE** - full-time equivalent tuition
14. **PellPCT** - percentage of students who receive government Pell grants

Institution

"Williams College","Yeshiva Sholom Shachna","Pitzer College","The Ailey School","Bates College","FIDM-Fashion Institute of Design & Merchandising-Orange County","Middlebury College","College of the Atlantic","DeVry University-North Carolina","Carnegie Mellon University","Rhode Island School of Design","University of Pennsylvania","Landmark College","Georgetown University","Columbia University in the City of New York","Ringling College of Art and Design","Beverly Hills Design Institute","Brown University","Manhattan School of Music","New York University","Claremont McKenna College","School of Visual Arts","Babson College","University of Southern California","Skidmore College","Yeshiva of Far Rockaway Derech Ayson Rabbinical Seminary","The New England Conservatory of Music","Colgate University","Scripps College","Colorado College","Northeastern University","Sewanee-The University of the South","Art Center College of Design","Bucknell University","New York Institute of Technology","Northwestern College-Chicago Campus","Columbus College of Art and Design","Boston College","New York School of Interior Design","School of the Art Institute of Chicago","Charles R Drew University of Medicine and Science","Union College","Harvard University","California Institute of the Arts","University of the Pacific","Whitman College","Shepherds College","American University","Barnard College","Carleton College","Trinity College","University of Puget Sound","Loyola Marymount University","Pratt Institute-Main","Tufts University","Dartmouth College","Connecticut College","Wake Forest University","Oberlin College","Harvey Mudd College","West Coast University-Ontario","Boston University","The Restaurant School at Walnut Hill College","Colby College","Bowdoin College","Chamberlain University-California","University of Miami","DeVry University-Pennsylvania","Massachusetts Institute of Technology","Art Academy of Cincinnati","FIDM-Fashion Institute of Design & Merchandising-San Diego","FIDM-Fashion Institute of Design & Merchandising-San Francisco","George Washington University","Lafayette College","Northwestern University","California College of the Arts","Franklin and Marshall College","The Creative Center","Hamilton College","Otis College of Art and Design","Duke University","FIDM-Fashion Institute of Design & Merchandising-Los Angeles","Reed College","Pepperdine University","Gettysburg College","Beacon College","MCPHS University","Bentley University","La Sierra University","The New School","Wesleyan University","University of San Diego","Aria Health School of Nursing","Maryland Institute College of Art","Embry-Riddle Aeronautical University-Daytona Beach","Hobart William Smith Colleges","Kenyon College","Quinnipiac University","Chapman University"

City

"Williamstown","Brooklym","Claremont","New York","Lewiston","Irvine","Middlebury","Bar Harbor","Charlotte","Pittsburgh","Providence","Philadelphia","Putney","Washington","New York","Sarasota","Beverly Hills","Providence","New York","New York","Claremont","New York","Wellesley","Los Angeles","Saratoga Springs","Far Rockaway","Boston","Hamilton","Claremont","Colorado Springs","Boston","Sewanee","Pasadena","Lewisburg","Old Westbury","Chicago","Columbus","Chestnut Hill","New York","Chicago","Los Angeles","Schenectady","Cambridge","Valencia","Stockton","Walla Walla","Union Grove","Washington","New York","Northfield","Hartford","Tacoma","Los Angeles","Brooklyn","Medford","Hanover","New London","Winston-Salem","Oberlin","Claremont","Ontario","Boston","Philadelphia","Waterville","Brunswick","Rancho Cordova","Coral Gables","Ft. Washington","Cambridge","Cincinnati","San Diego","San Francisco","Washington","Easton","Evanston","San Francisco","Lancaster","Omaha","Clinton","Los Angeles","Durham","Los Angeles","Portland","Malibu","Gettysburg","Leesburg","Boston","Waltham","Riverside","New York","Middletown","San Diego","Trevose","Baltimore","Daytona Beach","Geneva","Gambier","Hamden","Orange"

State

"MA","NY","CA","NY","ME","CA","VT","ME","NC","PA","RI","PA","VT","DC","NY","FL","CA","RI","NY","NY","CA","NY","MA","CA","NY","NY","MA","NY","CA","CO","MA","TN","CA","PA","NY","IL","OH","MA","NY","IL","CA","NY","MA","CA","CA","WA","WI","DC","NY","MN","CT","WA","CA","NY","MA","NH","CT","NC","OH","CA","CA","MA","PA","ME","ME","CA","FL","PA","MA","OH","CA","CA","DC","PA","IL","CA","PA","NE","NY","CA","NC","CA","OR","CA","PA","FL","MA","MA","CA","NY","CT","CA","PA","MD","FL","NY","OH","CT","CA"

UnID

168342,486026,121257,188669,160977,114415,230959,160959,482565,211440,217493,215062,247649,131496,190150,136774,475635,217156,192712,193900,112260,197151,164580,123961,195526,190752,167057,190099,123165,126678,167358,221519,109651,211291,194091,147749,202170,164924,194116,143048,111966,196866,166027,111081,120883,237057,481137,131159,189097,173258,130590,236328,117946,194578,168148,182670,128902,199847,204501,115409,458229,164988,215637,161086,161004,489353,135726,482608,166683,201061,248846,114390,131469,213385,147767,110370,212577,430485,191515,120403,198419,114354,209922,121150,212674,384254,166656,164739,117627,193654,130697,122436,212568,163295,133553,191630,203535,130226,111948

Zip

1267,11230,91711-6101,10019-4402,4240,92614-5610,5753,4609,28273,15213-3890,02903-2784,19104-6303,5346,20057-0001,10027,34234-5895,90211,2912,10027-4698,10012-1091,91711-6400,10010,02457-0310,90089,12866,11691-5219,02115-5018,13346-1398,91711-3905,80903,02115-5005,37383-1000,91103,17837,11568-8000,60630,43215,2467,10021,60603,90059,12308-2311,2138,91355-2397,95211-0197,99362,53182-1527,20016-8001,10027-6598,55057-4001,06106-3100,98416,90045-2659,11205,02155-5555,03755-3529,06320-4196,27106,44074,91711,91761,2215,19104,04901-8840,4011,95670,33146,19034,02139-4307,45202-1706,92101-4903,94108-5805,20052,18042-1768,60208,94107-2247,17604-3003,68164,13323,90045-3505,27708,90015-1421,97202-8199,90263,17325,34748,02115-5896,02452-4705,92505-8247,10011-8871,6459,92110-2492,19053-6939,21217-4134,32114-3900,14456,43022,6518,92866

Branches

1,1,1,1,1,4,2,1,18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,6,1,1,1,1,14,1,18,1,1,4,4,1,1,1,1,1,1,1,1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1

Region

1,2,8,2,1,8,1,1,5,2,1,2,1,2,2,5,8,1,2,2,8,2,1,8,2,2,1,2,8,7,1,5,8,2,2,3,3,1,2,3,8,2,1,8,8,8,3,2,2,4,1,8,8,2,1,1,1,5,3,8,8,1,2,1,1,8,5,2,1,3,8,8,2,2,3,8,2,4,2,8,5,8,8,8,2,5,1,1,8,2,1,8,2,2,5,2,3,1,8

HBCU

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

MenOnly

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

WomenOnly

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

AdmissionRate

0.176091625,0.945454545,0.13737325,0.292682927,0.226474981,0.41765873,0.161356163,0.64742268,0.912482727,0.217140969,0.341210168,0.094403618,0.361570248,0.168475271,0.068253668,0.781392694,0.24,0.093053412,0.462697538,0.318671366,0.0944497,0.744546649,0.245946653,0.166212233,0.290817994,0.875,0.354290569,0.287824637,0.298808736,0.159868254,0.28880011,0.436355415,0.692537313,0.299227615,0.725505752,0.70802005,0.755988024,0.311403509,0.347826087,0.593249428,0.25,0.368983153,0.054045747,0.236049601,0.659864713,0.510802881,0.795918367,0.259146184,0.167444492,0.226214341,0.33953565,0.788996561,0.53872353,0.576506285,0.142857143,0.10592503,0.351250213,0.303369984,0.280347499,0.128708134,0.923076923,0.294336798,0.97338403,0.187124987,0.148404177,0.664179104,0.377121249,0.912482727,0.079442692,0.305354559,0.41765873,0.41765873,0.402110797,0.282900406,0.106638177,0.648454045,0.363727887,0.74,0.260803059,0.929494712,0.108300969,0.41765873,0.31305872,0.368733687,0.426349765,0.483050847,0.844762077,0.463229079,0.459338473,0.600866956,0.178487592,0.513841671,0.555555556,0.570935252,0.711157584,0.57988294,0.2658129,0.764387877,0.540285469

SATAvg

1439,None,None,None,None,None,1394,None,None,1458,1214,1481,None,1422,1496,None,None,1459,None,1371,1413,1084,1281,1395,1240,None,None,1388,1353,None,1434,None,None,1312,1077,None,None,1378,957,1127,None,None,1506,None,1180,1324,None,1262,1375,1413,None,None,1244,1183,1445,1441,None,None,1364,1496,None,1328,None,1383,None,None,1323,None,1519,970,None,None,1301,1297,1470,None,None,None,1402,None,1460,None,1380,1251,None,None,1074,1198,906,1158,None,1237,None,1152,None,1260,1359,1096,1225

TuitionFTE

103259,53787,49158,45363,43687,43285,41298,40322,38788,38755,38394,37302,36396,36260,36218,36121,35820,34606,34110,33909,33729,33561,33470,33417,33084,33066,33038,32770,32758,32733,32455,32420,32408,32381,32365,32247,32241,32220,32200,32199,32151,32020,31997,31870,31711,31630,31630,31466,31326,31272,31237,31232,31134,31132,31123,30985,30955,30865,30700,30633,30618,30561,30544,30520,30410,30285,30282,30278,30274,30263,30145,30114,29987,29953,29833,29830,29826,29763,29739,29635,29630,29517,29475,29471,29470,29271,29100,29021,29011,28923,28902,28900,28685,28683,28660,28596,28519,28502,28432

PellPCT

0.1859,0.411,0.1584,0.2642,0.1032,0.337,0.1456,0.3303,0.6364,0.1208,0.1648,0.1338,0.2275,0.1198,0.2244,0.2895,0.5882,0.1506,0.139,0.2106,0.125,0.2282,0.1541,0.2169,0.1306,0.1176,0.1204,0.1213,0.0956,0.1317,0.1181,0.183,0.3253,0.1124,0.3591,0.7202,0.3759,0.1243,0.1312,0.1952,0.5647,0.1441,0.1145,0.2982,0.3585,0.1102,0.4,0.1658,0.1805,0.1301,0.1035,0.1397,0.1992,0.2081,0.1149,0.1423,0.1475,0.1024,0.0872,0.12,0.5348,0.1323,0.6985,0.091,0.1395,None,0.1337,0.5775,0.1736,0.4577,0.4034,0.3671,0.1419,0.0916,0.142,0.3157,0.1845,0.5714,0.1534,0.3766,0.1298,0.301,0.1678,0.178,0.13,0.2445,0.2883,0.134,0.4912,0.2151,0.1833,0.1625,0.5769,0.2188,0.2872,0.1502,0.0947,0.1548,0.176

#### 1: Create a dictionary that links the given variable names with the values given above

In [50]:
ziplist = '1267,11230,91711-6101,10019-4402,4240,92614-5610,5753,4609,28273,15213-3890,02903-2784,19104-6303,5346,20057-0001,10027,34234-5895,90211,2912,10027-4698,10012-1091,91711-6400,10010,02457-0310,90089,12866,11691-5219,02115-5018,13346-1398,91711-3905,80903,02115-5005,37383-1000,91103,17837,11568-8000,60630,43215,2467,10021,60603,90059,12308-2311,2138,91355-2397,95211-0197,99362,53182-1527,20016-8001,10027-6598,55057-4001,06106-3100,98416,90045-2659,11205,02155-5555,03755-3529,06320-4196,27106,44074,91711,91761,2215,19104,04901-8840,4011,95670,33146,19034,02139-4307,45202-1706,92101-4903,94108-5805,20052,18042-1768,60208,94107-2247,17604-3003,68164,13323,90045-3505,27708,90015-1421,97202-8199,90263,17325,34748,02115-5896,02452-4705,92505-8247,10011-8871,6459,92110-2492,19053-6939,21217-4134,32114-3900,14456,43022,6518,92866'
zipsplit = ziplist.split(",")

schools = {'Institution': ["Williams College", "Yeshiva Sholom Shachna","Pitzer College","The Ailey School","Bates College","FIDM-Fashion Institute of Design & Merchandising-Orange County","Middlebury College","College of the Atlantic","DeVry University-North Carolina","Carnegie Mellon University","Rhode Island School of Design","University of Pennsylvania","Landmark College","Georgetown University","Columbia University in the City of New York","Ringling College of Art and Design","Beverly Hills Design Institute","Brown University","Manhattan School of Music","New York University","Claremont McKenna College","School of Visual Arts","Babson College","University of Southern California","Skidmore College","Yeshiva of Far Rockaway Derech Ayson Rabbinical Seminary","The New England Conservatory of Music","Colgate University","Scripps College","Colorado College","Northeastern University","Sewanee-The University of the South","Art Center College of Design","Bucknell University","New York Institute of Technology","Northwestern College-Chicago Campus","Columbus College of Art and Design","Boston College","New York School of Interior Design","School of the Art Institute of Chicago","Charles R Drew University of Medicine and Science","Union College","Harvard University","California Institute of the Arts","University of the Pacific","Whitman College","Shepherds College","American University","Barnard College","Carleton College","Trinity College","University of Puget Sound","Loyola Marymount University","Pratt Institute-Main","Tufts University","Dartmouth College","Connecticut College","Wake Forest University","Oberlin College","Harvey Mudd College","West Coast University-Ontario","Boston University","The Restaurant School at Walnut Hill College","Colby College","Bowdoin College","Chamberlain University-California","University of Miami","DeVry University-Pennsylvania","Massachusetts Institute of Technology","Art Academy of Cincinnati","FIDM-Fashion Institute of Design & Merchandising-San Diego","FIDM-Fashion Institute of Design & Merchandising-San Francisco","George Washington University","Lafayette College","Northwestern University","California College of the Arts","Franklin and Marshall College","The Creative Center","Hamilton College","Otis College of Art and Design","Duke University","FIDM-Fashion Institute of Design & Merchandising-Los Angeles","Reed College","Pepperdine University","Gettysburg College","Beacon College","MCPHS University","Bentley University","La Sierra University","The New School","Wesleyan University","University of San Diego","Aria Health School of Nursing","Maryland Institute College of Art","Embry-Riddle Aeronautical University-Daytona Beach","Hobart William Smith Colleges","Kenyon College","Quinnipiac University","Chapman University"],
    'City': ["Williamstown","Brooklym","Claremont","New York","Lewiston","Irvine","Middlebury","Bar Harbor","Charlotte","Pittsburgh","Providence","Philadelphia","Putney","Washington","New York","Sarasota","Beverly Hills","Providence","New York","New York","Claremont","New York","Wellesley","Los Angeles","Saratoga Springs","Far Rockaway","Boston","Hamilton","Claremont","Colorado Springs","Boston","Sewanee","Pasadena","Lewisburg","Old Westbury","Chicago","Columbus","Chestnut Hill","New York","Chicago","Los Angeles","Schenectady","Cambridge","Valencia","Stockton","Walla Walla","Union Grove","Washington","New York","Northfield","Hartford","Tacoma","Los Angeles","Brooklyn","Medford","Hanover","New London","Winston-Salem","Oberlin","Claremont","Ontario","Boston","Philadelphia","Waterville","Brunswick","Rancho Cordova","Coral Gables","Ft. Washington","Cambridge","Cincinnati","San Diego","San Francisco","Washington","Easton","Evanston","San Francisco","Lancaster","Omaha","Clinton","Los Angeles","Durham","Los Angeles","Portland","Malibu","Gettysburg","Leesburg","Boston","Waltham","Riverside","New York","Middletown","San Diego","Trevose","Baltimore","Daytona Beach","Geneva","Gambier","Hamden","Orange"],
    'State': ["MA","NY","CA","NY","ME","CA","VT","ME","NC","PA","RI","PA","VT","DC","NY","FL","CA","RI","NY","NY","CA","NY","MA","CA","NY","NY","MA","NY","CA","CO","MA","TN","CA","PA","NY","IL","OH","MA","NY","IL","CA","NY","MA","CA","CA","WA","WI","DC","NY","MN","CT","WA","CA","NY","MA","NH","CT","NC","OH","CA","CA","MA","PA","ME","ME","CA","FL","PA","MA","OH","CA","CA","DC","PA","IL","CA","PA","NE","NY","CA","NC","CA","OR","CA","PA","FL","MA","MA","CA","NY","CT","CA","PA","MD","FL","NY","OH","CT","CA"],
    'UnID': [168342,486026,121257,188669,160977,114415,230959,160959,482565,211440,217493,215062,247649,131496,190150,136774,475635,217156,192712,193900,112260,197151,164580,123961,195526,190752,167057,190099,123165,126678,167358,221519,109651,211291,194091,147749,202170,164924,194116,143048,111966,196866,166027,111081,120883,237057,481137,131159,189097,173258,130590,236328,117946,194578,168148,182670,128902,199847,204501,115409,458229,164988,215637,161086,161004,489353,135726,482608,166683,201061,248846,114390,131469,213385,147767,110370,212577,430485,191515,120403,198419,114354,209922,121150,212674,384254,166656,164739,117627,193654,130697,122436,212568,163295,133553,191630,203535,130226,111948],
    'Zip': zipsplit,
    'Branches': [1,1,1,1,1,4,2,1,18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,6,1,1,1,1,14,1,18,1,1,4,4,1,1,1,1,1,1,1,1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1],
    'Region': [1,2,8,2,1,8,1,1,5,2,1,2,1,2,2,5,8,1,2,2,8,2,1,8,2,2,1,2,8,7,1,5,8,2,2,3,3,1,2,3,8,2,1,8,8,8,3,2,2,4,1,8,8,2,1,1,1,5,3,8,8,1,2,1,1,8,5,2,1,3,8,8,2,2,3,8,2,4,2,8,5,8,8,8,2,5,1,1,8,2,1,8,2,2,5,2,3,1,8],
    'HBCU': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'MenOnly': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'WomenOnly': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'AdmissionRate': [0.176091625,0.945454545,0.13737325,0.292682927,0.226474981,0.41765873,0.161356163,0.64742268,0.912482727,0.217140969,0.341210168,0.094403618,0.361570248,0.168475271,0.068253668,0.781392694,0.24,0.093053412,0.462697538,0.318671366,0.0944497,0.744546649,0.245946653,0.166212233,0.290817994,0.875,0.354290569,0.287824637,0.298808736,0.159868254,0.28880011,0.436355415,0.692537313,0.299227615,0.725505752,0.70802005,0.755988024,0.311403509,0.347826087,0.593249428,0.25,0.368983153,0.054045747,0.236049601,0.659864713,0.510802881,0.795918367,0.259146184,0.167444492,0.226214341,0.33953565,0.788996561,0.53872353,0.576506285,0.142857143,0.10592503,0.351250213,0.303369984,0.280347499,0.128708134,0.923076923,0.294336798,0.97338403,0.187124987,0.148404177,0.664179104,0.377121249,0.912482727,0.079442692,0.305354559,0.41765873,0.41765873,0.402110797,0.282900406,0.106638177,0.648454045,0.363727887,0.74,0.260803059,0.929494712,0.108300969,0.41765873,0.31305872,0.368733687,0.426349765,0.483050847,0.844762077,0.463229079,0.459338473,0.600866956,0.178487592,0.513841671,0.555555556,0.570935252,0.711157584,0.57988294,0.2658129,0.764387877,0.540285469],
    'SATAvg' : [1439,None,None,None,None,None,1394,None,None,1458,1214,1481,None,1422,1496,None,None,1459,None,1371,1413,1084,1281,1395,1240,None,None,1388,1353,None,1434,None,None,1312,1077,None,None,1378,957,1127,None,None,1506,None,1180,1324,None,1262,1375,1413,None,None,1244,1183,1445,1441,None,None,1364,1496,None,1328,None,1383,None,None,1323,None,1519,970,None,None,1301,1297,1470,None,None,None,1402,None,1460,None,1380,1251,None,None,1074,1198,906,1158,None,1237,None,1152,None,1260,1359,1096,1225],      
    'TuitionFTE': [103259,53787,49158,45363,43687,43285,41298,40322,38788,38755,38394,37302,36396,36260,36218,36121,35820,34606,34110,33909,33729,33561,33470,33417,33084,33066,33038,32770,32758,32733,32455,32420,32408,32381,32365,32247,32241,32220,32200,32199,32151,32020,31997,31870,31711,31630,31630,31466,31326,31272,31237,31232,31134,31132,31123,30985,30955,30865,30700,30633,30618,30561,30544,30520,30410,30285,30282,30278,30274,30263,30145,30114,29987,29953,29833,29830,29826,29763,29739,29635,29630,29517,29475,29471,29470,29271,29100,29021,29011,28923,28902,28900,28685,28683,28660,28596,28519,28502,28432],
    'PellPCT': [0.1859,0.411,0.1584,0.2642,0.1032,0.337,0.1456,0.3303,0.6364,0.1208,0.1648,0.1338,0.2275,0.1198,0.2244,0.2895,0.5882,0.1506,0.139,0.2106,0.125,0.2282,0.1541,0.2169,0.1306,0.1176,0.1204,0.1213,0.0956,0.1317,0.1181,0.183,0.3253,0.1124,0.3591,0.7202,0.3759,0.1243,0.1312,0.1952,0.5647,0.1441,0.1145,0.2982,0.3585,0.1102,0.4,0.1658,0.1805,0.1301,0.1035,0.1397,0.1992,0.2081,0.1149,0.1423,0.1475,0.1024,0.0872,0.12,0.5348,0.1323,0.6985,0.091,0.1395,None,0.1337,0.5775,0.1736,0.4577,0.4034,0.3671,0.1419,0.0916,0.142,0.3157,0.1845,0.5714,0.1534,0.3766,0.1298,0.301,0.1678,0.178,0.13,0.2445,0.2883,0.134,0.4912,0.2151,0.1833,0.1625,0.5769,0.2188,0.2872,0.1502,0.0947,0.1548,0.176]
          }

#### 2: Given your dictionary from (1) above, please show how you would check that  each dictionary item is of the same size

In [51]:
print (len(schools['Institution']), len(schools['City']), len(schools['State']), len(schools['UnID']), len(schools['Zip']), len(schools['Branches']), len(schools['Region']), len(schools['HBCU']), len(schools['MenOnly']), len(schools['WomenOnly']), len(schools['AdmissionRate']), len(schools['SATAvg']), len(schools['TuitionFTE']), len(schools['PellPCT']))

99 99 99 99 99 99 99 99 99 99 99 99 99 99

#### 3: Use your dictionary to create a dataframe

In [67]:
import pandas as pd
df = pd.DataFrame(schools)
df

,Institution,City,State,UnID,Zip,Branches,Region,HBCU,MenOnly,WomenOnly,AdmissionRate,SATAvg,TuitionFTE,PellPCT
0,Williams College,Williamstown,MA,168342,1267,1,1,0,0,0,0.176092,1439.0,103259,0.1859
1,Yeshiva Sholom Shachna,Brooklym,NY,486026,11230,1,2,0,0,0,0.945455,NaN,53787,0.4110
2,Pitzer College,Claremont,CA,121257,91711-6101,1,8,0,0,0,0.137373,NaN,49158,0.1584
3,The Ailey School,New York,NY,188669,10019-4402,1,2,0,0,0,0.292683,NaN,45363,0.2642
4,Bates College,Lewiston,ME,160977,4240,1,1,0,0,0,0.226475,NaN,43687,0.1032
5,FIDM-Fashion Institute of Design & Merchandisi...,Irvine,CA,114415,92614-5610,4,8,0,0,0,0.417659,NaN,43285,0.3370
6,Middlebury College,Middlebury,VT,230959,5753,2,1,0,0,0,0.161356,1394.0,41298,0.1456
7,College of the Atlantic,Bar Harbor,ME,160959,4609,1,1,0,0,0,0.647423,NaN,40322,0.3303
8,DeVry University-North Carolina,Charlotte,NC,482565,28273,18,5,0,0,0,0.912483,NaN,38788,0.6364
9,Carnegie Mellon University,Pittsburgh,PA,211440,15213-3890,1,2,0,0,0,0.217141,1458.0,38755,0.1208
10,Rhode Island School of Design,Providence,RI,217493,02903-2784,1,1,0,0,0,0.341210,1214.0,38394,0.1648
11,University of Pennsylvania,Philadelphia,PA,215062,19104-6303,1,2,0,0,0,0.094404,1481.0,37302,0.1338
12,Landmark College,Putney,VT,247649,5346,1,1,0,0,0,0.361570,NaN,36396,0.2275
13,Georgetown University,Washington,DC,131496,20057-0001,1,2,0,0,0,0.168475,1422.0,36260,0.1198
14,Columbia University in the City of New York,New York,NY,190150,10027,1,2,0,0,0,0.068254,1496.0,36218,0.2244
15,Ringling College of Art and Design,Sarasota,FL,136774,34234-5895,1,5,0,0,0,0.781393,NaN,36121,0.2895
16,Beverly Hills Design Institute,Beverly Hills,CA,475635,90211,1,8,0,0,0,0.240000,NaN,35820,0.5882
17,Brown University,Providence,RI,217156,2912,1,1,0,0,0,0.093053,1459.0,34606,0.1506
18,Manhattan School of Music,New York,NY,192712,10027-4698,1,2,0,0,0,0.462698,NaN,34110,0.1390
19,New York University,New York,NY,193900,10012-1091,1,2,0,0,0,0.318671,1371.0,33909,0.2106
20,Claremont McKenna College,Claremont,CA,112260,91711-6400,1,8,0,0,0,0.094450,1413.0,33729,0.1250
21,School of Visual Arts,New York,NY,197151,10010,1,2,0,0,0,0.744547,1084.0,33561,0.2282
22,Babson College,Wellesley,MA,164580,02457-0310,1,1,0,0,0,0.245947,1281.0,33470,0.1541
23,University of Southern California,Los Angeles,CA,123961,90089,1,8,0,0,0,0.166212,1395.0,33417,0.2169
24,Skidmore College,Saratoga Springs,NY,195526,12866,1,2,0,0,0,0.290818,1240.0,33084,0.1306
25,Yeshiva of Far Rockaway Derech Ayson Rabbinica...,Far Rockaway,NY,190752,11691-5219,1,2,0,0,0,0.875000,NaN,33066,0.1176
26,The New England Conservatory of Music,Boston,MA,167057,02115-5018,1,1,0,0,0,0.354291,NaN,33038,0.1204
27,Colgate University,Hamilton,NY,190099,13346-1398,1,2,0,0,0,0.287825,1388.0,32770,0.1213
28,Scripps College,Claremont,CA,123165,91711-3905,1,8,0,0,1,0.298809,1353.0,32758,0.0956
29,Colorado College,Colorado Springs,CO,126678,80903,1,7,0,0,0,0.159868,NaN,32733,0.1317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Art Academy of Cincinnati,Cincinnati,OH,201061,45202-1706,1,3,0,0,0,0.305355,970.0,30263,0.4577
70,FIDM-Fashion Institute of Design & Merchandisi...,San Diego,CA,248846,92101-4903,4,8,0,0,0,0.417659,NaN,30145,0.4034
71,FIDM-Fashion Institute of Design & Merchandisi...,San Francisco,CA,114390,94108-5805,4,8,0,0,0,0.417659,NaN,30114,0.3671
72,George Washington University,Washington,DC,131469,20052,1,2,0,0,0,0.402111,1301.0,29987,0.1419
73,Lafayette College,Easton,PA,213385,18042-1768,1,2,0,0,0,0.282900,1297.0,29953,0.0916
74,Northwestern University,Evanston,IL,147767,60208,1,3,0,0,0,0.106638,1470.0,29833,0.1420
75,California College of the Arts,San Francisco,CA,110370,94107-2247,1,8,0,0,0,0.648454,NaN,29830,0.3157
76,Franklin and Marshall College,Lancaster,PA,212577,17604-3003,1,2,0,0,0,0.363728,NaN,29826,0.1845
77,The Creative Center,Omaha,NE,430485,68164,1,4,0,0,0,0.740000,NaN,29763,0.5714
78,Hamilton College,Clinton,NY,191515,13323,1,2,0,0,0,0.260803,1402.0,29739,0.1534
79,Otis College of Art and Design,Los Angeles,CA,120403,90045-3505,1,8,0,0,0,0.929495,NaN,29635,0.3766
80,Duke University,Durham,NC,198419,27708,1,5,0,0,0,0.108301,1460.0,29630,0.1298
81,FIDM-Fashion Institute of Design & Merchandisi...,Los Angeles,CA,114354,90015-1421,4,8,0,0,0,0.417659,NaN,29517,0.3010
82,Reed College,Portland,OR,209922,97202-8199,1,8,0,0,0,0.313059,1380.0,29475,0.1678
83,Pepperdine University,Malibu,CA,121150,90263,1,8,0,0,0,0.368734,1251.0,29471,0.1780
84,Gettysburg College,Gettysburg,PA,212674,17325,1,2,0,0,0,0.426350,NaN,29470,0.1300
85,Beacon College,Leesburg,FL,384254,34748,1,5,0,0,0,0.483051,NaN,29271,0.2445
86,MCPHS University,Boston,MA,166656,02115-5896,1,1,0,0,0,0.844762,1074.0,29100,0.2883
87,Bentley University,Waltham,MA,164739,02452-4705,1,1,0,0,0,0.463229,1198.0,29021,0.1340
88,La Sierra University,Riverside,CA,117627,92505-8247,1,8,0,0,0,0.459338,906.0,29011,0.4912
89,The New School,New York,NY,193654,10011-8871,1,2,0,0,0,0.600867,1158.0,28923,0.2151
90,Wesleyan University,Middletown,CT,130697,6459,1,1,0,0,0,0.178488,NaN,28902,0.1833
91,University of San Diego,San Diego,CA,122436,92110-2492,1,8,0,0,0,0.513842,1237.0,28900,0.1625
92,Aria Health School of Nursing,Trevose,PA,212568,19053-6939,1,2,0,0,0,0.555556,NaN,28685,0.5769
93,Maryland Institute College of Art,Baltimore,MD,163295,21217-4134,1,2,0,0,0,0.570935,1152.0,28683,0.2188
94,Embry-Riddle Aeronautical University-Daytona B...,Daytona Beach,FL,133553,32114-3900,2,5,0,0,0,0.711158,NaN,28660,0.2872
95,Hobart William Smith Colleges,Geneva,NY,191630,14456,1,2,0,0,0,0.579883,1260.0,28596,0.1502
96,Kenyon College,Gambier,OH,203535,43022,1,3,0,0,0,0.265813,1359.0,28519,0.0947
97,Quinnipiac University,Hamden,CT,130226,6518,1,1,0,0,0,0.764388,1096.0,28502,0.1548
98,Chapman University,Orange,CA,111948,92866,1,8,0,0,0,0.540285,1225.0,28432,0.1760

#### 4: Please show only the top 3 entries of your dataframe

In [55]:
df.iloc[0:3]

,Institution,City,State,UnID,Zip,Branches,Region,HBCU,MenOnly,WomenOnly,AdmissionRate,SATAvg,TuitionFTE,PellPCT
0,Williams College,Williamstown,MA,168342,1267,1,1,0,0,0,0.176092,1439.0,103259,0.1859
1,Yeshiva Sholom Shachna,Brooklym,NY,486026,11230,1,2,0,0,0,0.945455,NaN,53787,0.4110
2,Pitzer College,Claremont,CA,121257,91711-6101,1,8,0,0,0,0.137373,NaN,49158,0.1584

#### 5: Please fill any None value with 0

In [61]:
df.fillna(0, inplace=True)
df.iloc[0:3]

,Institution,City,State,UnID,Zip,Branches,Region,HBCU,MenOnly,WomenOnly,AdmissionRate,SATAvg,TuitionFTE,PellPCT
0,Williams College,Williamstown,MA,168342,1267,1,1,0,0,0,0.176092,1439.0,103259,0.1859
1,Yeshiva Sholom Shachna,Brooklym,NY,486026,11230,1,2,0,0,0,0.945455,0.0,53787,0.4110
2,Pitzer College,Claremont,CA,121257,91711-6101,1,8,0,0,0,0.137373,0.0,49158,0.1584

#### 6: What's the average amount of tuition at these schools? <br> 7: Does that differ from the median?

In [98]:
df.describe()
print('Average:','${:,.0f}'.format(df['TuitionFTE'].mean()))
print('Median:', '${:,.0f}'.format(df['TuitionFTE'].median()))
print('Average tuition is $33,256, which is greater than the median of $31,272.')

Average: $33,256
Median: $31,272
Average tuition is $33,256, which is greater than the median of $31,272.

#### 8: How many schools are HBCUs? Men-only? Women-only?

In [79]:
print('HBCU:', df['HBCU'].sum())
print('Men-only:', df['MenOnly'].sum())
print('Women-only:', df['WomenOnly'].sum())
print('There are 0 HBCUs and 0 Men-only schools. There are 2 Women-only schools.')

HBCU: 0
Men-only: 0
Women-only: 2
There are 0 HBCUs and 0 Men-only schools. There are 2 Women-only schools.

#### 9: Please pick a threshold of what you think is expensive and then create a new column that indicates whether that school is cheap or expensive

In [125]:
df['Expensive?'] = df['TuitionFTE'].apply(lambda x: 'Expensive' if x>=50000 else 'Cheap')
df.iloc[0:3]

,Institution,City,State,UnID,Zip,Branches,Region,HBCU,MenOnly,WomenOnly,AdmissionRate,SATAvg,TuitionFTE,PellPCT,Expensive?
0,Williams College,Williamstown,MA,168342,1267,1,1,0,0,0,0.176092,1439.0,103259,0.1859,Expensive
1,Yeshiva Sholom Shachna,Brooklym,NY,486026,11230,1,2,0,0,0,0.945455,NaN,53787,0.4110,Expensive
2,Pitzer College,Claremont,CA,121257,91711-6101,1,8,0,0,0,0.137373,NaN,49158,0.1584,Cheap

#### 10: For the expensive school is (9) above, could you divide them to show a table where the number of Pell recepients is greater than 15%

In [126]:
subdf = df[(df['Expensive?'] == 'Expensive') & (df['PellPCT'] > 0.15)]
subdf

,Institution,City,State,UnID,Zip,Branches,Region,HBCU,MenOnly,WomenOnly,AdmissionRate,SATAvg,TuitionFTE,PellPCT,Expensive?
0,Williams College,Williamstown,MA,168342,1267,1,1,0,0,0,0.176092,1439.0,103259,0.1859,Expensive
1,Yeshiva Sholom Shachna,Brooklym,NY,486026,11230,1,2,0,0,0,0.945455,NaN,53787,0.4110,Expensive